/**
 * Seed script for top_100_books.
 * Reads .example data/Top100.csv. display_order is arbitrary (for stable DB fetch only).
 * The API serves 2 per genre per batch; which 2 from each genre is randomised per session.
 * Run: node scripts/seed-top-100.mjs > supabase/seed_top_100_books.sql
 */

import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..');
const csvPath = join(repoRoot, '.example data', 'Top100.csv');

// Seeded RNG (mulberry32) for deterministic shuffle
function mulberry32(seed) {
	return function () {
		let t = (seed += 0x6d2b79f5);
		t = Math.imul(t ^ (t >>> 15), t | 1);
		t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
		return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
	};
}

function shuffleWithSeed(arr, seed) {
	const rng = mulberry32(seed);
	const out = [...arr];
	for (let i = out.length - 1; i > 0; i--) {
		const j = Math.floor(rng() * (i + 1));
		[out[i], out[j]] = [out[j], out[i]];
	}
	return out;
}

const csvText = readFileSync(csvPath, 'utf8');
const lines = csvText.trim().split(/\r?\n/);
const headers = lines[0].split(',').map((h) => h.trim());
const genreOrder = Object.fromEntries(headers.map((g, i) => [g, i]));

// Collect (book_id, genre) per genre: 10 books per genre
const byGenre = {};
headers.forEach((g) => (byGenre[g] = []));

for (let row = 1; row <= 10; row++) {
	const cells = lines[row].split(',');
	headers.forEach((genre, col) => {
		const bookId = parseInt(cells[col].trim(), 10);
		if (!Number.isNaN(bookId)) byGenre[genre].push(bookId);
	});
}

// Build flat list (book_id, genre) — one row per cell in the CSV
const entries = [];
for (const genre of headers) {
	for (const book_id of byGenre[genre]) {
		entries.push({ book_id, genre });
	}
}

// Assign display_order 1..100 in random order (no canonical order stored in DB)
const indices = shuffleWithSeed([...Array(100).keys()].map((i) => i + 1), 12345);
const rows = entries.map((e, i) => ({
	...e,
	display_order: indices[i]
}));

// Emit SQL (escape single quotes in genre)
function esc(s) {
	return s.replace(/'/g, "''");
}

console.log('-- Seed data for top_100_books (2 per genre per batch; which 2 is randomised per session in API). Generated by scripts/seed-top-100.mjs');
console.log('-- Run in Supabase SQL Editor after migration 20260318000000_add_top_100_books.sql');
console.log('');
console.log('insert into public.top_100_books (book_id, genre, display_order)');
console.log('values');
const values = rows.map((r) => `  (${r.book_id}, '${esc(r.genre)}', ${r.display_order})`).join(',\n');
console.log(values);
console.log('on conflict (book_id) do update set genre = excluded.genre, display_order = excluded.display_order;');
